---
- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Set up UFW Rules
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ ssh_port }}"
    - "80"
    - "443"

#- name: Enable UFW
#  community.general.ufw:
#    state: enabled