- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone GitHub Repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    clone: yes
    update: yes
    version: main
    force: yes

- name: Copy .env.sample to .env
  copy:
    src: "{{ repo_dest }}/.env.sample"
    dest: "{{ repo_dest }}/.env"
    remote_src: yes

- name: Copy traefik.env.sample to .env
  copy:
    src: "{{ repo_dest }}/data/traefik/.env.sample"
    dest: "{{ repo_dest }}/data/traefik/.env"
    remote_src: yes

- name: Copy traefik-crowdsec-bouncer.env.sample to .env
  copy:
    src: "{{ repo_dest }}/data/traefik-crowdsec-bouncer/.env.sample"
    dest: "{{ repo_dest }}/data/traefik-crowdsec-bouncer/.env"
    remote_src: yes

- name: Copy socket-proxy.env.sample to .env
  copy:
    src: "{{ repo_dest }}/data/socket-proxy/.env.sample"
    dest: "{{ repo_dest }}/data/socket-proxy/.env"
    remote_src: yes

- name: Copy crowdsec.env.sample to .env
  copy:
    src: "{{ repo_dest }}/data/crowdsec/.env.sample"
    dest: "{{ repo_dest }}/data/crowdsec/.env"
    remote_src: yes

- name: Replace Variables in .env
  lineinfile:
    path: "{{ repo_dest }}/.env"
    regexp: "^ABSOLUTE_PATH="
    line: "ABSOLUTE_PATH={{ repo_dest }}"

- name: Replace Domain Variable in .env
  lineinfile:
    path: "{{ repo_dest }}/.env"
    regexp: "^SERVICES_TRAEFIK_LABELS_TRAEFIK_HOST="
    line: "SERVICES_TRAEFIK_LABELS_TRAEFIK_HOST=HOST(`{{ traeffikdashboarddomain }}`)"