- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone GitHub Repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    clone: yes
    update: yes
    version: main
    force: yes

- name: Copy sample files to their destinations if they do not exist
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    force: no
  with_items:
    - { src: "{{ repo_dest }}/.env.sample", dest: "{{ repo_dest }}/.env" }
    - { src: "{{ repo_dest }}/data/traefik/.env.sample", dest: "{{ repo_dest }}/data/traefik/.env" }
    - { src: "{{ repo_dest }}/data/traefik-crowdsec-bouncer/.env.sample", dest: "{{ repo_dest }}/data/traefik-crowdsec-bouncer/.env" }
    - { src: "{{ repo_dest }}/data/socket-proxy/.env.sample", dest: "{{ repo_dest }}/data/socket-proxy/.env" }
    - { src: "{{ repo_dest }}/data/crowdsec/.env.sample", dest: "{{ repo_dest }}/data/crowdsec/.env" }
    - { src: "{{ repo_dest }}/data/traefik/traefik.yml.sample", dest: "{{ repo_dest }}/data/traefik/traefik.yml" }
    - { src: "{{ repo_dest }}/data/traefik/certs/acme_letsencrypt.json.sample", dest: "{{ repo_dest }}/data/traefik/certs/acme_letsencrypt.json" }
    - { src: "{{ repo_dest }}/data/traefik/certs/tls_letsencrypt.json.sample", dest: "{{ repo_dest }}/data/traefik/certs/tls_letsencrypt.json" }
    - { src: "{{ repo_dest }}/data/traefik/dynamic_conf/http.middlewares.default.yml.sample", dest: "{{ repo_dest }}/data/traefik/dynamic_conf/http.middlewares.default.yml" }
    - { src: "{{ repo_dest }}/data/traefik/dynamic_conf/http.middlewares.default-security-headers.yml.sample", dest: "{{ repo_dest }}/data/traefik/dynamic_conf/http.middlewares.default-security-headers.yml" }
    - { src: "{{ repo_dest }}/data/traefik/dynamic_conf/http.middlewares.gzip.yml.sample", dest: "{{ repo_dest }}/data/traefik/dynamic_conf/http.middlewares.gzip.yml" }
    - { src: "{{ repo_dest }}/data/traefik/dynamic_conf/http.middlewares.traefik-bouncer.yml.sample", dest: "{{ repo_dest }}/data/traefik/dynamic_conf/http.middlewares.traefik-bouncer.yml" }
    - { src: "{{ repo_dest }}/data/traefik/dynamic_conf/http.middlewares.traefik-dashboard-auth.yml.sample", dest: "{{ repo_dest }}/data/traefik/dynamic_conf/http.middlewares.traefik-dashboard-auth.yml" }
    - { src: "{{ repo_dest }}/data/traefik/dynamic_conf/tls.yml.sample", dest: "{{ repo_dest }}/data/traefik/dynamic_conf/tls.yml" }

- name: Set permissions for sensitive files
  file:
    path: "{{ item }}"
    mode: "{{ file_permission_mode | default('0600') }}"
  with_items:
    - "{{ repo_dest }}/data/traefik/certs/acme_letsencrypt.json"
    - "{{ repo_dest }}/data/traefik/certs/tls_letsencrypt.json"

- name: Replace Variables in .env
  lineinfile:
    path: "{{ repo_dest }}/.env"
    regexp: "^ABSOLUTE_PATH="
    line: "ABSOLUTE_PATH={{ repo_dest }}"

- name: Replace Domain Variable in .env
  lineinfile:
    path: "{{ repo_dest }}/.env"
    regexp: "^SERVICES_TRAEFIK_LABELS_TRAEFIK_HOST=.*"
    line: "SERVICES_TRAEFIK_LABELS_TRAEFIK_HOST=HOST(`{{ traeffikdashboarddomain }}`)"

- name: Set correct permissions for .env file
  file:
    path: "{{ item }}"
    mode: '0644'
  loop:
    - "{{ repo_dest }}/.env"
