---
- name: Create docker group
  group:
    name: docker
    state: present

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add Admin User to docker group
  user:
    name: "{{ admin_user }}"
    groups: docker
    append: yes

- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository
  shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    executable: /bin/bash
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Create Docker directory
  file:
    path: "{{ docker_directory }}"
    state: directory
    owner: "{{ admin_user }}"
    group: docker
    mode: '0750'