---
- name: Add CrowdSec repository
  shell: curl -s https://install.crowdsec.net | sudo sh
  args:
    creates: /etc/apt/sources.list.d/crowdsec.list
  become: true

- name: Install CrowdSec Firewall Bouncer for UFW + IPTables
  apt:
    name: crowdsec-firewall-bouncer-iptables
    state: present
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Generate secure Bouncer key
  shell: openssl rand -base64 48 | tr -dc 'a-zA-Z0-9!@#$%^&*()-_=+[]{}<>?|'
  register: bouncer_firewall_key
  changed_when: false

- name: Display generated Bouncer key
  debug:
    msg: "Generated BOUNCER_KEY_FIREWALL: {{ bouncer_firewall_key.stdout }}"

- name: Store Bouncer key in .env file
  lineinfile:
    path: "{{ repo_dest }}/.env"
    line: 'BOUNCER_KEY_FIREWALL="{{ bouncer_firewall_key.stdout }}"'
    create: yes
  become: true

- name: Enable CrowdSec Firewall Bouncer service
  systemd:
    name: crowdsec-firewall-bouncer
    enabled: yes
    state: restarted
  become: true

- name: Check status of CrowdSec Firewall Bouncer service
  command: systemctl status crowdsec-firewall-bouncer
  register: bouncer_status
  changed_when: false
  become: true

- name: Show service status
  debug:
    msg: "{{ bouncer_status.stdout_lines }}"

- name: List registered CrowdSec bouncers
  command: docker exec crowdsec cscli bouncers list
  register: bouncers_list
  changed_when: false
  become: true

- name: Show registered bouncers
  debug:
    msg: "{{ bouncers_list.stdout_lines }}"